project:
  type: website
  output-dir: docs

execute: 
  freeze: auto

website:
  title: "Luciano's blog"
  navbar:
    right:
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/LucianoDeBenedictis/blog
      - text: Electronics
        href: https://bentfishbowl.wixsite.com/electronics
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



